# Generated by Django 5.2.10 on 2026-01-31 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_content",
                    models.TextField(blank=True, help_text="Raw log file content"),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="api.log",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host",
                "verbose_name_plural": "Hosts",
                "ordering": ["hostname"],
                "unique_together": {("log", "hostname")},
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("changed", "Changed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("tasks_ok", models.IntegerField(default=0)),
                ("tasks_changed", models.IntegerField(default=0)),
                ("tasks_failed", models.IntegerField(default=0)),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Line number in raw log where play starts",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Play order position (0-indexed)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="api.host",
                    ),
                ),
            ],
            options={
                "verbose_name": "Play",
                "verbose_name_plural": "Plays",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Task order (0-indexed)"
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Line number in raw log where task starts",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("changed", "Changed"),
                            ("failed", "Failed"),
                            ("fatal", "Fatal"),
                            ("skipping", "Skipped"),
                            ("unreachable", "Unreachable"),
                            ("ignored", "Ignored"),
                            ("rescued", "Rescued"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True, help_text="Error message when task fails", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_list",
                        to="api.play",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["host", "order"], name="api_play_host_id_ed6279_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["status", "-date"], name="api_play_status_a80565_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["play", "order"], name="api_task_play_id_0fb2aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="api_task_status_2aef03_idx"),
        ),
    ]
