# Generated by Django 5.2.9 on 2026-01-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_host_id_alter_log_id_alter_play_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
