# Generated by Django 5.2.9 on 2026-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_make_play_date_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={
                "ordering": ["order"],
                "verbose_name": "Play",
                "verbose_name_plural": "Plays",
            },
        ),
        migrations.RemoveIndex(
            model_name="play",
            name="api_play_host_id_78cea4_idx",
        ),
        migrations.AddField(
            model_name="play",
            name="line_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Line number in raw log where play starts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Play order position (0-indexed)"
            ),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(
                fields=["host", "order"], name="api_play_host_id_ed6279_idx"
            ),
        ),
    ]
